[workspace]
channels = ["https://prefix.dev/conda-forge"]
preview = ["pixi-build"]

[package]
version = "0.5.0"

[package.build.backend]
name = "pixi-build-python"
version = "*"

[package.build.config]
ignore-pypi-mapping = false
