name: Deploy documentation

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10'
      - name: Install dependencies
        run: pip install '.[docs]'
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build docs
        run: make -C scripts/sphinx html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./scripts/sphinx/build/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
